### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by allenimitsg** [mathLab/WaveBEMapp-DTMB-5415#2]
First time to submit new issue.

system: Windows 7, 64.
python: python 3.7, 
Pycharm: community 2018.3.5

Dependencies and installation: 
OCC == 0.18; (The installation of OCC == 0.17 gets stuck in solving environment.)
PyGeM from git;
active_subspaces from git.

But the Pycharm reports error:
Traceback (most recent call last):
  File "D:/Pycharm/WaveBEMapp-DTMB-5415-master/app.py", line 539, in <module>
    window = Window(None)
  File "D:/Pycharm/WaveBEMapp-DTMB-5415-master/app.py", line 205, in __init__
    self.precompute_active_subspace()
  File "D:/Pycharm/WaveBEMapp-DTMB-5415-master/app.py", line 349, in precompute_active_subspace
    import active_subspaces as ac
  File "C:\Users\Allen\Anaconda3\lib\site-packages\active_subspaces\__init__.py", line 1, in <module>
    from active_subspaces.base import *
  File "C:\Users\Allen\Anaconda3\lib\site-packages\active_subspaces\base.py", line 2, in <module>
    from utils.utils import process_inputs
ModuleNotFoundError: No module named 'utils.utils'

Does utils.utils come from active_subspaces, or other package?

**Comment by mtezzele** [comment]
Dear @allenimitsg, 
utils.utils comes from active_subspaces. Unfortunately this repository is not maintained anymore and it depends on old versions of other packages. Moreover I never tested it on windows. This was just a showcase.

**Comment by allenimitsg** [comment]
Dear @mtezzele ,
I got it. Thanks a lot.
